### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by mihye1128** [camp-team/new-kumamoto#1]
## MTG
- [x] issue確認MTG (2020.12.3 21:00 start)

### 事前準備
- [x] 要件定義・設計 @K-Yuki1019
- [x] issueを立てる @K-Yuki1019
- [x] XDプロトタイプ作成 @K-Yuki1019 
- [x] サービス名考案 @yuuki-kouno
## 環境構築
- [x] Angular @peyo-code 
- [x] Angular CLI: 11.0.3 @K-Yuki1019
- [x] Angular update 9 -> 11 @mihye1128 
- [x] AngularMaterial @mihye1128 
- [x] AngularFire  @mihye1128 
- [x] 自動Prettier  @peyo-code 
- [x] 自動deploy @peyo-code

## 画面作成
###共通画面
- [x] Header作成　@mihye1128 #13 
- [x] Footer作成 @yuuki-kouno 
### Home画面(LP)　@Robinson-R1127 (メイン)　@K-Yuki1019 (サポート)
- [ ] Heroコンポーネント 
- [ ] Aboutコンポーネント 
- [ ] CatchCopyコンポーネント #8 
### My page画面
- [ ] My page @peyo-code 
- [ ] History-list(カードまとめる画面) @peyo-code 
- [ ] History-Card @peyo-code 
- [ ] Delete ~User-Dialog(My page画面でのみ) @yuuki-kouno
### Setting画面(言葉登録画面) @K-Yuki1019
- [ ] setting #18 
- [ ] Message-List(HTMLで最新のHistoryにhistoryIDを持たせて、最新のプルリクが一番に表示されるように) #19 
- [ ] Message-card #21 
- [ ] Create-Message-Dialog #22 
- [ ] Delete-Message-Dialog #22 
### 404ページ
- [ ] Not-Found @yuuki-kouno
## 機能実装
- [x] ログイン/ ログアウト(初ログインした際に辞書に適当なのを一つ作る) @mihye1128 #12 
- [ ] messageのCRUD+Getメソッド (主要機能なのですぐ作る) @K-Yuki1019 #26 
- [ ] interface作成 @K-Yuki1019 #24 
- [ ] Guard(CanLoad/ CanActivate @Robinson-R1127 #11 
- [ ] HistoryService(getHistory→History一覧を持ってくる) @peyo-code

## Functions(Githubにプッシュした時)
- [x] createHistory @mihye1128
- [ ] deleteHistory(バッチ処理) @yuuki-kouno

## MindNode
![image](https://user-images.githubusercontent.com/61979156/101231174-c9c14380-36ec-11eb-954f-e20697867e66.png)

## XD
![image](https://user-images.githubusercontent.com/61979156/101231191-dfcf0400-36ec-11eb-9b80-2cb89fe43e55.png)
